spring.application.name=URL-Shortner-Project

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=29041225
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
















## This is the "switch" that creates the table from your code
#spring.jpa.hibernate.ddl-auto=update
## This will show you the "CREATE TABLE" command in the console
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.sql.init.mode=always